global:
  smtp_smarthost: 'localhost:587'
  smtp_from: 'alerts@mosia.app'
  smtp_auth_username: ''
  smtp_auth_password: ''

route:
  group_by: ['alertname']
  group_wait: 10s
  group_interval: 10s
  repeat_interval: 1h
  receiver: 'web.hook'
  routes:
  - match:
      severity: critical
    receiver: 'critical-alerts'
  - match:
      severity: warning
    receiver: 'warning-alerts'

receivers:
- name: 'web.hook'
  webhook_configs:
  - url: 'http://localhost:5001/webhook'
    send_resolved: true

- name: 'critical-alerts'
  email_configs:
  - to: 'devops@mosia.app'
    subject: '🚨 CRITICAL: Mosia System Alert'
    body: |
      Alert: {{ .GroupLabels.alertname }}
      
      Summary: {{ range .Alerts }}{{ .Annotations.summary }}{{ end }}
      
      Description: {{ range .Alerts }}{{ .Annotations.description }}{{ end }}
      
      Details:
      {{ range .Alerts }}
      - Alert: {{ .Labels.alertname }}
      - Instance: {{ .Labels.instance }}
      - Severity: {{ .Labels.severity }}
      - Started: {{ .StartsAt }}
      {{ end }}
    headers:
      Subject: '🚨 CRITICAL: Mosia System Alert - {{ .GroupLabels.alertname }}'
  
  slack_configs:
  - api_url: '${SLACK_WEBHOOK_URL}'
    channel: '#alerts-critical'
    title: '🚨 Critical Alert: {{ .GroupLabels.alertname }}'
    text: |
      {{ range .Alerts }}
      *Alert:* {{ .Labels.alertname }}
      *Summary:* {{ .Annotations.summary }}
      *Description:* {{ .Annotations.description }}
      *Severity:* {{ .Labels.severity }}
      *Instance:* {{ .Labels.instance }}
      {{ end }}

- name: 'warning-alerts'
  email_configs:
  - to: 'devops@mosia.app'
    subject: '⚠️ WARNING: Mosia System Alert'
    body: |
      Alert: {{ .GroupLabels.alertname }}
      
      Summary: {{ range .Alerts }}{{ .Annotations.summary }}{{ end }}
      
      Description: {{ range .Alerts }}{{ .Annotations.description }}{{ end }}
    headers:
      Subject: '⚠️ WARNING: Mosia System Alert - {{ .GroupLabels.alertname }}'

inhibit_rules:
- source_match:
    severity: 'critical'
  target_match:
    severity: 'warning'
  equal: ['alertname', 'dev', 'instance']