name: Backend CI/CD Pipeline

on:
  push:
    branches: [ main, develop ]
    paths:
      - 'backend/main_service/moscala/**'
      - '.github/workflows/backend-ci.yml'
  pull_request:
    branches: [ main, develop ]
    paths:
      - 'backend/main_service/moscala/**'

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: mosia/backend-api

jobs:
  test:
    name: Test & Quality Check
    runs-on: ubuntu-latest
    
    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_PASSWORD: postgres
          POSTGRES_USER: postgres
          POSTGRES_DB: mosia_test
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432
      
      redis:
        image: redis:7-alpine
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 6379:6379

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Java
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '21'
        cache: 'sbt'

    - name: Cache SBT
      uses: actions/cache@v4
      with:
        path: |
          ~/.sbt
          ~/.ivy2/cache
          ~/.coursier
        key: ${{ runner.os }}-sbt-${{ hashFiles('backend/main_service/moscala/build.sbt', 'backend/main_service/moscala/project/**') }}
        restore-keys: |
          ${{ runner.os }}-sbt-

    - name: Run tests
      working-directory: backend/main_service/moscala
      env:
        DB_DEFAULT_URL: jdbc:postgresql://localhost:5432/mosia_test
        DB_DEFAULT_USER: postgres
        DB_DEFAULT_PASSWORD: postgres
        KAFKA_BOOTSTRAP_SERVER: localhost:9092
      run: |
        sbt test

    - name: Check code formatting
      working-directory: backend/main_service/moscala
      run: |
        sbt check

    - name: Run security scan
      working-directory: backend/main_service/moscala
      run: |
        sbt dependencyCheck

    - name: Generate coverage report
      working-directory: backend/main_service/moscala
      run: |
        sbt coverage test coverageReport

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v3
      with:
        file: backend/main_service/moscala/target/scala-3.3.6/scoverage-report/scoverage.xml
        flags: backend
        name: backend-coverage

  security-scan:
    name: Security Scanning
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Run dependency security check
      working-directory: backend/main_service/moscala
      run: |
        echo "Running built-in dependency security check..."
        sbt dependencyCheck

  build:
    name: Build & Push Container
    runs-on: ubuntu-latest
    needs: [test, security-scan]
    if: github.ref == 'refs/heads/main'
    
    permissions:
      contents: read
      packages: write

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Log in to Container Registry
      uses: docker/login-action@v3
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Extract metadata
      id: meta
      uses: docker/metadata-action@v5
      with:
        images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
        tags: |
          type=ref,event=branch
          type=ref,event=pr
          type=sha,prefix={{branch}}-
          type=raw,value=latest,enable={{is_default_branch}}

    - name: Build and push container image
      uses: docker/build-push-action@v5
      with:
        context: backend/main_service/moscala
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
        cache-from: type=gha
        cache-to: type=gha,mode=max
        platforms: linux/amd64,linux/arm64

  deploy-staging:
    name: Deploy to Staging
    runs-on: ubuntu-latest
    needs: build
    if: github.ref == 'refs/heads/main'
    environment: staging
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Configure kubectl
      uses: azure/k8s-set-context@v3
      with:
        method: kubeconfig
        kubeconfig: ${{ secrets.KUBECONFIG_STAGING }}

    - name: Deploy to staging
      working-directory: devops/k8s
      run: |
        kubectl apply -f staging/ -n mosia-staging
        kubectl set image deployment/backend-api backend-api=${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ github.sha }} -n mosia-staging
        kubectl rollout status deployment/backend-api -n mosia-staging --timeout=300s

    - name: Run smoke tests
      run: |
        # Wait for deployment to be ready
        sleep 30
        # Run basic health check
        curl -f https://staging-api.mosia.app/health || exit 1