name: Backend CI (Simplified)

on:
  push:
    branches: [ main, develop ]
    paths:
      - 'backend/main_service/moscala/**'

jobs:
  test:
    name: Test & Quality Check
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Java
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '21'
        cache: 'sbt'

    - name: Run tests
      working-directory: backend/main_service/moscala
      run: |
        echo "Running simplified tests..."
        sbt compile
        # sbt test  # 当你有测试时取消注释

    - name: Check code formatting
      working-directory: backend/main_service/moscala
      run: |
        sbt check

    - name: Build application
      working-directory: backend/main_service/moscala
      run: |
        sbt assembly
        echo "✅ Build completed successfully!"

  # 只有main分支才构建Docker镜像
  build:
    name: Build Container (No Push)
    runs-on: ubuntu-latest
    needs: test
    if: github.ref == 'refs/heads/main'
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Build Docker image (test only)
      uses: docker/build-push-action@v5
      with:
        context: backend/main_service/moscala
        push: false  # 不推送，只构建测试
        tags: mosia/backend-api:test