name: Frontend CI/CD Pipeline

on:
  push:
    branches: [ main, develop ]
    paths:
      - 'frontend/mobile/**'
      - '.github/workflows/frontend-ci.yml'
  pull_request:
    branches: [ main, develop ]
    paths:
      - 'frontend/mobile/**'

jobs:
  test:
    name: Flutter Test & Analysis
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.24.0'
        channel: 'stable'

    - name: Get dependencies
      working-directory: frontend/mobile
      run: flutter pub get

    - name: Verify formatting
      working-directory: frontend/mobile
      run: dart format --output=none --set-exit-if-changed .

    - name: Analyze code
      working-directory: frontend/mobile
      run: flutter analyze --fatal-infos

    - name: Run tests
      working-directory: frontend/mobile
      run: flutter test --coverage

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v3
      with:
        file: frontend/mobile/coverage/lcov.info
        flags: frontend
        name: frontend-coverage

  build-android:
    name: Build Android APK
    runs-on: ubuntu-latest
    needs: test
    if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/develop'
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.24.0'
        channel: 'stable'

    - name: Setup Java
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '17'

    - name: Get dependencies
      working-directory: frontend/mobile
      run: flutter pub get

    - name: Build Android APK
      working-directory: frontend/mobile
      run: flutter build apk --release

    - name: Upload APK artifact
      uses: actions/upload-artifact@v4
      with:
        name: android-apk
        path: frontend/mobile/build/app/outputs/flutter-apk/app-release.apk

  build-ios:
    name: Build iOS IPA
    runs-on: macos-latest
    needs: test
    if: github.ref == 'refs/heads/main'
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.24.0'
        channel: 'stable'

    - name: Get dependencies
      working-directory: frontend/mobile
      run: flutter pub get

    - name: Build iOS (no sign)
      working-directory: frontend/mobile
      run: flutter build ios --release --no-codesign

    - name: Upload iOS build artifact
      uses: actions/upload-artifact@v4
      with:
        name: ios-build
        path: frontend/mobile/build/ios/iphoneos/Runner.app